import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTopButton from "./components/shred/ScrollToTopButton";
// import MarqueeBanner from "./components/MarqueeBanner";
import ProductGridTwo from "./components/ProductGridTwo";
// import NavScrollExample from "./components/NavScrollExample";
import 'bootstrap/dist/css/bootstrap.min.css';
import ImageCard from "./components/ImageCard";
import ProductCards from "./components/ProductCards";
import ProductGrid from "./components/ProductGrid";
import Footer from "./components/shred/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
   
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <head>
        {/* FontAwesome CDN */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKB4Imkb9x5WbM6r0Hkn7Gc4jJ7R8F3eH45SFTJ2pW7XYtND+i+M8lw1Ym6Y5qlhk6Vd/w8eA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        {children}
{/* <NavScrollExample /> */}
  <ScrollToTopButton />
  {/* <MarqueeBanner /> */}
<ImageCard/>
{/* <Home/> */}
<ProductGridTwo/>
<ProductCards/>
<ProductGrid/>
<Footer/>
      </body>
    </html>
  );
}
